name: Video Renderer
on:
  # Trigger manually or via webhook
  workflow_dispatch:
    inputs:
      video_id:
        description: 'Video ID to render'
        required: true
        type: string
  # Also run on a schedule to check for queued videos
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  
  # Trigger via repository dispatch (webhook)
  repository_dispatch:
    types: [render_video]

jobs:
  render-video:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    # Cache system dependencies
    - name: Cache system dependencies
      id: cache-system-deps
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: system-deps-${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}
        restore-keys: |
          system-deps-${{ runner.os }}-
        
    - name: Install system dependencies
      if: steps.cache-system-deps.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libcairo2-dev \
          libgirepository1.0-dev \
          ffmpeg \
          libpango1.0-dev \
          portaudio19-dev \
          libasound2-dev \
          libsndfile1-dev \
          libfftw3-dev \
          libatlas-base-dev
          
    - name: Fix apt cache permissions
      run: |
        sudo find /var/cache/apt -type f -exec sudo chmod 644 {} +
        sudo find /var/cache/apt -type d -exec sudo chmod 755 {} +

    # Cache Python dependencies
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-python-deps
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-python3.11-${{ hashFiles('requirements-github-actions.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-python3.11-
          pip-${{ runner.os }}-
          
    # Cache installed packages in virtual environment
    - name: Cache virtual environment
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: venv
        key: venv-${{ runner.os }}-python3.11-${{ hashFiles('requirements-github-actions.txt') }}
        restore-keys: |
          venv-${{ runner.os }}-python3.11-
          
    - name: Create virtual environment and install Python dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        # Use GitHub Actions specific requirements (excludes problematic audio deps)
        pip install -r requirements-github-actions.txt
        
    - name: Activate virtual environment
      if: steps.cache-venv.outputs.cache-hit == 'true'
      run: |
        source venv/bin/activate
        echo "PATH=$PWD/venv/bin:$PATH" >> $GITHUB_ENV
        
    - name: Test dependencies
      run: |
        source venv/bin/activate
        python test_github_actions_fix.py
        
    - name: Set up environment variables
      env:
        APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
        APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        ELEVENLABS_VOICE: "true"  # Enable ElevenLabs voice generation
      run: |
        echo "Environment variables set"
        
    - name: Check for queued videos
      id: check_queue
      env:
        APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
        APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
      run: |
        source venv/bin/activate
        python scripts/check_video_queue.py
        
    - name: Render videos
      if: steps.check_queue.outputs.videos_found == 'true'
      env:
        APPWRITE_ENDPOINT: ${{ secrets.APPWRITE_ENDPOINT }}
        APPWRITE_PROJECT_ID: ${{ secrets.APPWRITE_PROJECT_ID }}
        APPWRITE_API_KEY: ${{ secrets.APPWRITE_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
        ELEVENLABS_VOICE: "true"  # Enable ElevenLabs voice generation
        VIDEO_ID: ${{ github.event.inputs.video_id || github.event.client_payload.video_id }}
      run: |
        source venv/bin/activate
        python scripts/github_video_renderer.py
        
    - name: Upload artifacts (for debugging)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: video-render-logs
        path: |
          output/
          *.log
        retention-days: 7 
